# Generated by Django 3.2.13 on 2023-04-07 09:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_daily_hitcounts', models.IntegerField(default=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(default='normal', max_length=50)),
                ('user_nvmid', models.CharField(max_length=50, null=True)),
                ('keyword', models.CharField(max_length=50, null=True)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_shopping', models.BooleanField(default=False)),
                ('is_grouped_item', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('end_date', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('price', models.FloatField(default=0.0)),
                ('is_turned_on', models.BooleanField(default=False)),
                ('today_hitcount', models.IntegerField(default=0)),
                ('total_hitcount', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_shopping', models.BooleanField(default=False)),
                ('ip_address', models.CharField(max_length=50)),
                ('access_time', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('access_url', models.CharField(max_length=50)),
                ('keyword', models.CharField(max_length=50)),
                ('user_nvmid', models.CharField(max_length=50)),
                ('stay_time', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='traffic_service.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
